<?php
/**
 * Customize Admin Menu
 * This is a lightweight jquery and CSS helpers for customixing the admin menu globally
 * This module doesn't do anything other than add some js and css files
 */

//Define module path as a constant
define( 'SEVENLAND_ADMIN_MENU_MODULE_PATH', drupal_get_path( 'module', 'sevenland_admin_menu' ) );

//Add in Alt css
drupal_add_css( SEVENLAND_ADMIN_MENU_MODULE_PATH .'/css/alt.admin-menu.css' );

//Add javascript, this adds the id's to the menu items.
drupal_add_js( SEVENLAND_ADMIN_MENU_MODULE_PATH .'/js/jquery.functions.js' );